name: Python package

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: [3.12]

    name: Tests | Python ${{ matrix.python }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Run tests with xvfb
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" python -m unittest discover
